<a href="https://colab.research.google.com/github/deepaksirohiwal/Deep_Learning_with_PyTorch/blob/main/Tensors_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
#imports
import torch
import numpy as np

## What are Tensors?

Tensors are a specialized data structure that are very similar to arrays and matrices. In PyTorch, we use tensors to encode the inputs and outputs of a model, as well as the model’s parameters.

Tensors are similar to NumPy’s ndarrays, except that tensors can run on GPUs or other hardware accelerators. In fact, tensors and NumPy arrays can often share the same underlying memory, eliminating the need to copy data

In [2]:
# Creating a 2x3 matrix (2 rows, 3 columns)
data = [[1, 2, 3], [4, 5, 6]]
tensor = torch.tensor(data)

print(tensor)


tensor([[1, 2, 3],
        [4, 5, 6]])


In [3]:
# Tensors can be created from numpy array
np_array= np.array(data)
tensor_np=torch.from_numpy(np_array)
print(tensor_np)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [4]:
# new tensor retains the properties of the argument tensor unless explicitly overridden
x_ones=torch.ones_like(tensor)
print(f"Ones tensors: \n {x_ones}\n")

x_rand= torch.rand_like(tensor, dtype=torch.float)
print(f"Random Tensor: \n {x_rand}\n")

Ones tensors: 
 tensor([[1, 1, 1],
        [1, 1, 1]])

Random Tensor: 
 tensor([[0.5507, 0.9277, 0.7524],
        [0.8279, 0.8253, 0.4156]])



In [5]:
# tensor with radom or contant values
shape=(2,3)
rand_tensor=torch.rand(shape)
ones_tensor=torch.ones(shape)
zeros_tensor=torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor} \n")

Random Tensor: 
 tensor([[0.2086, 0.2974, 0.5643],
        [0.2029, 0.6316, 0.7974]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



In [6]:
# attributes of tensors
tensor_x= torch.rand(3,4)

print(f"Shape of tensor: {tensor_x.shape}")
print(f"Datatype of tensor: {tensor_x.dtype}")
print(f"Device tensor is stored on: {tensor_x.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


Each of these operations can be run on the GPU (at typically higher speeds than on a CPU). If you’re using Colab, allocate a GPU by going to Runtime > Change runtime type > GPU.

By default, tensors are created on the CPU. We need to explicitly move tensors to the GPU using .to method (after checking for GPU availability)

In [7]:
if torch.cuda.is_available():
  tensor=tensor.to("cuda")

In [8]:
# Sclicing
tensor_x= torch.rand(4,4)
print(tensor_x)

tensor([[0.9635, 0.8880, 0.9644, 0.8368],
        [0.9456, 0.0074, 0.1670, 0.5148],
        [0.6015, 0.9124, 0.0446, 0.8916],
        [0.1510, 0.8542, 0.8114, 0.4277]])


In [9]:
print(f"First row: {tensor_x[0]}")
print(f"First column: {tensor_x[:,0]}")
print(f"Last column: {tensor_x[...,-1]}")
tensor_x[:,1]=0
print(tensor_x)

First row: tensor([0.9635, 0.8880, 0.9644, 0.8368])
First column: tensor([0.9635, 0.9456, 0.6015, 0.1510])
Last column: tensor([0.8368, 0.5148, 0.8916, 0.4277])
tensor([[0.9635, 0.0000, 0.9644, 0.8368],
        [0.9456, 0.0000, 0.1670, 0.5148],
        [0.6015, 0.0000, 0.0446, 0.8916],
        [0.1510, 0.0000, 0.8114, 0.4277]])


## Arithmetic operations

In [10]:
tensor_y= torch.ones(4,4)
if torch.cuda.is_available():
  tensor_y=tensor_y.to("cuda")
# Arithmetic operations
# tensor_y.T returns the transpose of the tensor
y1= tensor_y @ tensor_y.T
y2= tensor_y.matmul(tensor_y.T)

print(f"y1: {y1}")
print(f"y2: {y2}")

# element wise product
z1=tensor_y*tensor_y
z2=tensor_y.mul(tensor_y)

print(f"z1: {z1}")
print(f"z2: {z2}")

y1: tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]])
y2: tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]])
z1: tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
z2: tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


Single-element tensors If you have a one-element tensor, for example by aggregating all values of a tensor into one value, you can convert it to a Python numerical value using item()

In [12]:
# single element tensors
agg= tensor_y.sum()
agg_item= agg.item()
print(agg_item, type(agg_item))


16.0 <class 'float'>


## Inplace operation
Operations that store the result into the operand are called in-place. They are denoted by a `_` suffix. For example: `x.copy_(y)`, `x.t_()`, will change x.

In [14]:
print(f"{tensor_y}\n")
tensor_y.add_(5)
print(tensor_y)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

tensor([[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]])


## Bridge with numpy
Tensors on the CPU and NumPy arrays can share their underlying memory locations, and changing one will change the other.


---
You can convert data between PyTorch tensors and NumPy arrays without necessarily copying the data. This sharing of memory is possible due to the design and interoperability of PyTorch and NumPy, making it efficient to switch between the two libraries.

Here's how this works:

1. **Shared Memory:** Both PyTorch and NumPy offer a way to work with numerical data in a way that is compatible with each other. When you create a PyTorch tensor from a NumPy array or vice versa, they can potentially share the same memory location.

2. **Efficient Conversion:** When you convert data between a PyTorch tensor and a NumPy array, the libraries often do not perform a full data copy. Instead, they create a view that points to the same memory location.

3. **In-Place Modifications:** Since they share memory, if you modify the values in one (either through PyTorch or NumPy operations), the other will immediately reflect those changes. This can be very useful for interoperability and memory efficiency.

However, it's important to note that not all conversions between PyTorch and NumPy result in shared memory. Sometimes, a conversion might require a full copy of the data if the underlying data type or layout is incompatible. Also, sharing memory between the two libraries can be risky if you're not aware of the potential side effects.

To ensure you understand how memory sharing works and to avoid unexpected behavior, it's recommended to handle conversions deliberately and carefully, especially in complex scenarios where you're dealing with large datasets or complex computations.


In [15]:
# Create a NumPy array
numpy_array = np.array([1, 2, 3])

# Convert NumPy array to PyTorch tensor
pytorch_tensor = torch.from_numpy(numpy_array)

# Modify the tensor in-place
pytorch_tensor[0] = 99

# The corresponding element in the NumPy array also changes
print(numpy_array)


[99  2  3]
